/**
 * The Daily Signal Layer — one normalised row per calendar day, joining
 * money, mood, journal, notes, habits and planner onto a single key.
 *
 * Server-only, but deliberately **not** `"use server"`: it has to be
 * callable from API routes as well as from server actions, exactly as
 * `features/budget/summary.js` already is.
 *
 * Two invariants hold everywhere below, and everything downstream depends
 * on them:
 *
 * 1. **The series is gap-explicit.** Every day between `from` and `to`
 *    appears, including days with no activity at all. Detectors need to
 *    see the gaps to know they are gaps.
 *
 * 2. **Missing is null, not zero.** `moodScore: null` means "not
 *    recorded"; `spendTotalPaisa: 0` alongside `hasMoneyData: false` means
 *    "nothing logged". Collapsing those two is the easiest way to
 *    manufacture a correlation that isn't there — a user who only logs
 *    expenses on stressful days would otherwise look like someone who
 *    spends nothing when calm.
 */

import connectDB from "@/lib/mongoose";
import Expense from "@/models/Expense";
import Category from "@/models/Category";
import DailyJournal from "@/models/DailyJournal";
import QuickNote from "@/models/QuickNote";
import HabitLog from "@/models/HabitLog";
import PlannerGoal from "@/models/PlannerGoal";
import { categoryMap } from "@/features/budget/utils";
import { MOOD_SCORE, NOTE_TYPES, PLANNER_DAY_KEYS, MAX_WINDOW_DAYS } from "./constants";
import {
  addDays,
  dateKeyFromUtcMidnight,
  dateKeyRange,
  dayDiff,
  dayOfMonth,
  dowIndex,
  isDateKey,
  isWeekendKey,
  mondayOfKey,
  utcMidnightFromKey,
} from "./dates";

/**
 * @typedef {object} DailySignal
 * @property {string} date              'YYYY-MM-DD'
 * @property {number} dow               0 = Monday … 6 = Sunday
 * @property {boolean} isWeekend
 * @property {number} dayOfMonth
 * @property {number} spendTotalPaisa
 * @property {number} spendNeedPaisa
 * @property {number} spendWantPaisa
 * @property {number} spendSavingsPaisa
 * @property {number} spendRecurringPaisa   recurring / auto-generated only
 * @property {number} spendTotalManualPaisa total excluding recurring
 * @property {number} spendWantManualPaisa  wants excluding recurring
 * @property {Record<string, number>} spendByCategoryId
 * @property {number} expenseCount
 * @property {number} largestExpensePaisa
 * @property {number} largestManualExpensePaisa  ignores recurring entries
 * @property {boolean} hasMoneyData
 * @property {string|null} mood
 * @property {number|null} moodScore    1–5, null when unset — never imputed
 * @property {boolean} hasMood
 * @property {number} journalWords
 * @property {boolean} hasJournal
 * @property {number|null} sentiment  -1..1 from journal text, null when unextracted
 * @property {boolean} hasSentiment
 * @property {string|null} energy     'low' | 'medium' | 'high'
 * @property {number} noteCount
 * @property {Record<string, number>} noteCountByType
 * @property {number} habitsTracked
 * @property {number} habitsDone
 * @property {number|null} habitRate    null when nothing was tracked
 * @property {Record<string, boolean>} habitByName
 * @property {number} plannerDone
 * @property {number} plannerMissed
 * @property {number} plannerPending
 */

/**
 * Every daily signal for a user across a window, ascending by date.
 *
 * Each collection is read once with a single indexed range scan and
 * bucketed in memory — never one query per day. Windows longer than
 * `MAX_WINDOW_DAYS` are clamped forward from `to`.
 *
 * @param {string} userId
 * @param {string} from 'YYYY-MM-DD' local date key, inclusive
 * @param {string} to   'YYYY-MM-DD' local date key, inclusive
 * @returns {Promise<DailySignal[]>}
 */
export async function getDailySignals(userId, from, to) {
  if (!userId) return [];
  if (!isDateKey(from) || !isDateKey(to)) {
    throw new Error(`getDailySignals: expected 'YYYY-MM-DD' keys, got ${from}..${to}`);
  }
  if (dayDiff(from, to) < 0) return [];

  const start =
    dayDiff(from, to) >= MAX_WINDOW_DAYS ? addDays(to, -(MAX_WINDOW_DAYS - 1)) : from;

  await connectDB();

  const [expenses, categories, journals, notes, habitLogs, plannerGoals] =
    await Promise.all([
      Expense.find({
        userId,
        deletedAt: null,
        date: { $gte: start, $lte: to },
      })
        .select("amountPaisa categoryId date isRecurring autoGenerated")
        .lean(),

      Category.find({ userId }).select("type").lean(),

      DailyJournal.find({ userId, date: { $gte: start, $lte: to } })
        .select("date mood content signals")
        .lean(),

      QuickNote.find({
        userId,
        deletedAt: null,
        date: { $gte: start, $lte: to },
      })
        .select("date type")
        .lean(),

      // HabitLog.date is a UTC-midnight Date, so the range must be built
      // in UTC too — see dates.js.
      HabitLog.find({
        userId,
        date: { $gte: utcMidnightFromKey(start), $lte: utcMidnightFromKey(to) },
      })
        .select("date habitName completed")
        .lean(),

      // A goal's week can start before the window and still cover days
      // inside it, so reach back to that Monday.
      PlannerGoal.find({
        userId,
        weekStart: { $gte: mondayOfKey(start), $lte: to },
      })
        .select("weekStart days")
        .lean(),
    ]);

  return buildDailySignals({
    from: start,
    to,
    expenses,
    categories,
    journals,
    notes,
    habitLogs,
    plannerGoals,
  });
}

/**
 * The pure half of the signal layer: raw documents in, daily rows out.
 *
 * Separated from the query so the bucketing — especially the date
 * normalisation, which is the one thing here that can silently corrupt
 * every pattern in the product — is testable without a database.
 *
 * @returns {DailySignal[]}
 */
export function buildDailySignals({
  from,
  to,
  expenses = [],
  categories = [],
  journals = [],
  notes = [],
  habitLogs = [],
  plannerGoals = [],
}) {
  const days = dateKeyRange(from, to);
  const rows = new Map(days.map((date) => [date, emptySignal(date)]));

  const byCategoryId = categoryMap(categories);

  // ── money ────────────────────────────────────────────────────────────
  for (const expense of expenses) {
    if (expense.deletedAt) continue;
    const row = rows.get(expense.date);
    if (!row) continue;

    const paisa = Number(expense.amountPaisa) || 0;
    const categoryId = String(expense.categoryId);
    const isAuto = Boolean(expense.isRecurring || expense.autoGenerated);

    row.spendTotalPaisa += paisa;
    row.expenseCount += 1;
    row.hasMoneyData = true;
    row.spendByCategoryId[categoryId] =
      (row.spendByCategoryId[categoryId] ?? 0) + paisa;
    if (paisa > row.largestExpensePaisa) row.largestExpensePaisa = paisa;

    if (isAuto) {
      row.spendRecurringPaisa += paisa;
    } else {
      row.spendTotalManualPaisa += paisa;
      if (paisa > row.largestManualExpensePaisa) row.largestManualExpensePaisa = paisa;
    }

    // An expense whose category was deleted contributes to the total but
    // to no need/want/savings bucket — better than guessing a type.
    const type = byCategoryId[categoryId]?.type;
    if (type === "need") row.spendNeedPaisa += paisa;
    else if (type === "savings") row.spendSavingsPaisa += paisa;
    else if (type === "want") {
      row.spendWantPaisa += paisa;
      // Rent and subscriptions are not discretionary behaviour, so the
      // rhythm and purchase detectors work off the manual figure.
      if (!isAuto) row.spendWantManualPaisa += paisa;
    }
  }

  // ── mood and journal ─────────────────────────────────────────────────
  for (const journal of journals) {
    const row = rows.get(journal.date);
    if (!row) continue;

    if (journal.mood && MOOD_SCORE[journal.mood] !== undefined) {
      row.mood = journal.mood;
      row.moodScore = MOOD_SCORE[journal.mood];
      row.hasMood = true;
    }

    row.journalWords = countWords(journal.content);
    row.hasJournal = row.journalWords > 0;

    // Sentiment extracted from what was actually written. Independent of
    // `mood`, which the user has to remember to set — on a day with words
    // but no mood, this is the only emotional signal there is.
    const sentiment = journal.signals?.sentiment;
    if (typeof sentiment === "number" && Number.isFinite(sentiment)) {
      row.sentiment = sentiment;
      row.hasSentiment = true;
      row.energy = journal.signals?.energy ?? null;
    }
  }

  // ── quick notes ──────────────────────────────────────────────────────
  for (const note of notes) {
    if (note.deletedAt) continue;
    const row = rows.get(note.date);
    if (!row) continue;
    row.noteCount += 1;
    const type = NOTE_TYPES.includes(note.type) ? note.type : "note";
    row.noteCountByType[type] += 1;
  }

  // ── habits ───────────────────────────────────────────────────────────
  for (const log of habitLogs) {
    const row = rows.get(dateKeyFromUtcMidnight(log.date));
    if (!row) continue;
    const done = Boolean(log.completed);
    row.habitByName[log.habitName] = done;
    row.habitsTracked += 1;
    if (done) row.habitsDone += 1;
  }
  for (const row of rows.values()) {
    row.habitRate =
      row.habitsTracked > 0 ? row.habitsDone / row.habitsTracked : null;
  }

  // ── planner ──────────────────────────────────────────────────────────
  for (const goal of plannerGoals) {
    for (let i = 0; i < PLANNER_DAY_KEYS.length; i++) {
      const row = rows.get(addDays(goal.weekStart, i));
      if (!row) continue;
      const status = goal.days?.[PLANNER_DAY_KEYS[i]];
      if (status === "done") row.plannerDone += 1;
      else if (status === "missed") row.plannerMissed += 1;
      else if (status === "pending") row.plannerPending += 1;
    }
  }

  return days.map((date) => rows.get(date));
}

/**
 * Per-domain day counts over a signal series — the input to the coverage
 * gate and to the readiness screen's honest "not yet" states.
 */
export function computeCoverage(signals) {
  const rows = signals ?? [];
  const count = (predicate) => rows.reduce((n, r) => n + (predicate(r) ? 1 : 0), 0);

  return {
    totalDays: rows.length,
    from: rows[0]?.date ?? null,
    to: rows[rows.length - 1]?.date ?? null,
    mood: count((r) => r.hasMood),
    sentiment: count((r) => r.hasSentiment),
    money: count((r) => r.hasMoneyData),
    journal: count((r) => r.hasJournal),
    notes: count((r) => r.noteCount > 0),
    habits: count((r) => r.habitsTracked > 0),
    planner: count((r) => r.plannerDone + r.plannerMissed + r.plannerPending > 0),
    activeDays: count(
      (r) => r.hasMood || r.hasMoneyData || r.hasJournal || r.noteCount > 0 || r.habitsTracked > 0
    ),
  };
}

/** A day on which nothing has been recorded yet. */
function emptySignal(date) {
  return {
    date,
    dow: dowIndex(date),
    isWeekend: isWeekendKey(date),
    dayOfMonth: dayOfMonth(date),

    spendTotalPaisa: 0,
    spendNeedPaisa: 0,
    spendWantPaisa: 0,
    spendSavingsPaisa: 0,
    spendRecurringPaisa: 0,
    spendTotalManualPaisa: 0,
    spendWantManualPaisa: 0,
    spendByCategoryId: {},
    expenseCount: 0,
    largestExpensePaisa: 0,
    largestManualExpensePaisa: 0,
    hasMoneyData: false,

    mood: null,
    moodScore: null,
    hasMood: false,

    journalWords: 0,
    hasJournal: false,
    sentiment: null,
    hasSentiment: false,
    energy: null,
    noteCount: 0,
    noteCountByType: Object.fromEntries(NOTE_TYPES.map((t) => [t, 0])),

    habitsTracked: 0,
    habitsDone: 0,
    habitRate: null,
    habitByName: {},

    plannerDone: 0,
    plannerMissed: 0,
    plannerPending: 0,
  };
}

/** Whitespace-delimited word count — the Lifeline's definition. */
function countWords(text) {
  const trimmed = String(text ?? "").trim();
  if (!trimmed) return 0;
  return trimmed.split(/\s+/).length;
}
