import { dto } from "@/lib/dto";

/**
 * An expense as the client sees it.
 *
 * `_id` keeps its Mongo name because every budget component keys on it.
 * Deliberately absent: `userId` (the caller already knows who they are),
 * `deletedAt`, `sourceRef`, `fingerprint`, `updatedAt` and `__v`.
 */
export const toExpenseDTO = dto([
  "_id",
  "amountPaisa",
  "currency",
  "categoryId",
  "date",
  "note",
  "paymentMethod",
  "tags",
  "isRecurring",
  "recurrence",
  "autoGenerated",
  "source",
  "createdAt",
]);

/** An income entry as the client sees it. */
export const toIncomeDTO = dto([
  "_id",
  "amountPaisa",
  "currency",
  "category",
  "date",
  "note",
  "source",
  "createdAt",
]);
