"use client";

import * as React from "react";
import { Pencil, Trash2, Repeat } from "lucide-react";
import { toast } from "sonner";
import { formatDate } from "@/lib/utils";
import { formatMoney } from "@/lib/money";
import { Badge } from "@/components/ui/badge";
import { useBudgetStore } from "../store";
import { PAYMENT_METHODS } from "../constants";

const PAYMENT_LABEL = Object.fromEntries(
  PAYMENT_METHODS.map((p) => [p.id, p.label])
);

/**
 * One expense record. Editing happens in {@link ExpenseDialog}, opened
 * by the parent — the row itself stays a read-only line so the list
 * never reflows into a form.
 */
const SWIPE_COMMIT = -96; // px of leftward drag that deletes on release

export function ExpenseRow({ expense, category, onEdit }) {
  const deleteExpense = useBudgetStore((s) => s.deleteExpense);
  const undoDeleteExpense = useBudgetStore((s) => s.undoDeleteExpense);

  // Swipe-to-delete (touch only — pointer users keep the hover buttons).
  const [swipeX, setSwipeX] = React.useState(0);
  const tracking = React.useRef(null);

  async function handleDelete() {
    try {
      const removed = await deleteExpense(expense._id);
      toast("Expense deleted.", {
        action: {
          label: "Undo",
          onClick: () => undoDeleteExpense(removed),
        },
      });
    } catch {
      toast.error("Could not delete expense.");
    }
  }

  function onTouchStart(e) {
    const t = e.touches[0];
    tracking.current = { x: t.clientX, y: t.clientY, axis: null };
  }

  function onTouchMove(e) {
    const t = tracking.current;
    if (!t) return;
    const dx = e.touches[0].clientX - t.x;
    const dy = e.touches[0].clientY - t.y;
    // Decide once: horizontal gesture swipes, vertical gesture scrolls.
    if (t.axis === null) t.axis = Math.abs(dx) > Math.abs(dy) + 6 ? "h" : "v";
    if (t.axis !== "h") return;
    setSwipeX(Math.max(Math.min(dx, 0), SWIPE_COMMIT - 24));
  }

  function onTouchEnd() {
    const t = tracking.current;
    tracking.current = null;
    if (t?.axis === "h" && swipeX <= SWIPE_COMMIT) {
      setSwipeX(0);
      handleDelete();
      return;
    }
    setSwipeX(0);
  }

  const meta = [
    PAYMENT_LABEL[expense.paymentMethod] || null,
    expense.note || null,
  ].filter(Boolean);

  return (
    <div className="relative overflow-hidden rounded-lg">
      {/* Delete affordance revealed behind the row while swiping. */}
      <div
        aria-hidden="true"
        className="absolute inset-0 flex items-center justify-end rounded-lg bg-negative pr-5 text-white"
        style={{ opacity: swipeX < -8 ? 1 : 0 }}
      >
        <Trash2 className="h-4 w-4" />
      </div>
      <div
        onTouchStart={onTouchStart}
        onTouchMove={onTouchMove}
        onTouchEnd={onTouchEnd}
        className="relative bg-card"
        style={{
          transform: swipeX ? `translateX(${swipeX}px)` : undefined,
          transition: tracking.current ? "none" : "transform 0.2s ease-out",
        }}
      >
    <div className="group flex items-center justify-between gap-3 rounded-lg px-2 py-2.5 text-sm hover:bg-accent/50">
      <div className="flex min-w-0 items-center gap-3">
        <span
          className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-base"
          style={{ background: `${category?.color || "#64748b"}22` }}
          aria-hidden="true"
        >
          {category?.icon || "🏷️"}
        </span>
        <div className="min-w-0">
          <div className="flex items-center gap-1.5">
            <span className="truncate font-medium">
              {category?.name || "Uncategorized"}
            </span>
            {expense.isRecurring && (
              <Repeat
                className="h-3 w-3 shrink-0 text-muted-foreground"
                aria-label="Recurring"
              />
            )}
            {expense.autoGenerated && (
              <Badge variant="outline" className="shrink-0 px-1.5 py-0 text-[10px]">
                auto
              </Badge>
            )}
          </div>
          {meta.length > 0 && (
            <p className="truncate text-xs text-muted-foreground">
              {meta.join(" · ")}
            </p>
          )}
        </div>
      </div>
      <div className="flex shrink-0 items-center gap-3">
        <span className="hidden text-xs text-muted-foreground sm:inline">
          {formatDate(expense.date)}
        </span>
        <span className="tabular-nums font-medium">
          {formatMoney(expense.amountPaisa)}
        </span>
        <div className="flex opacity-0 transition-opacity focus-within:opacity-100 group-hover:opacity-100">
          <button
            onClick={() => onEdit(expense)}
            aria-label="Edit expense"
            className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
          >
            <Pencil className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={handleDelete}
            aria-label="Delete expense"
            className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-destructive"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
    </div>
      </div>
    </div>
  );
}
