"use client";

import { Pencil, Trash2, Repeat } from "lucide-react";
import { toast } from "sonner";
import { formatDate } from "@/lib/utils";
import { formatMoney } from "@/lib/money";
import { Badge } from "@/components/ui/badge";
import { useBudgetStore } from "../store";
import { PAYMENT_METHODS } from "../constants";

const PAYMENT_LABEL = Object.fromEntries(
  PAYMENT_METHODS.map((p) => [p.id, p.label])
);

/**
 * One expense record. Editing happens in {@link ExpenseDialog}, opened
 * by the parent — the row itself stays a read-only line so the list
 * never reflows into a form.
 */
export function ExpenseRow({ expense, category, onEdit }) {
  const deleteExpense = useBudgetStore((s) => s.deleteExpense);
  const undoDeleteExpense = useBudgetStore((s) => s.undoDeleteExpense);

  async function handleDelete() {
    try {
      const removed = await deleteExpense(expense._id);
      toast("Expense deleted.", {
        action: {
          label: "Undo",
          onClick: () => undoDeleteExpense(removed),
        },
      });
    } catch {
      toast.error("Could not delete expense.");
    }
  }

  const meta = [
    PAYMENT_LABEL[expense.paymentMethod] || null,
    expense.note || null,
  ].filter(Boolean);

  return (
    <div className="group flex items-center justify-between gap-3 rounded-lg px-2 py-2.5 text-sm hover:bg-accent/50">
      <div className="flex min-w-0 items-center gap-3">
        <span
          className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-base"
          style={{ background: `${category?.color || "#64748b"}22` }}
          aria-hidden="true"
        >
          {category?.icon || "🏷️"}
        </span>
        <div className="min-w-0">
          <div className="flex items-center gap-1.5">
            <span className="truncate font-medium">
              {category?.name || "Uncategorized"}
            </span>
            {expense.isRecurring && (
              <Repeat
                className="h-3 w-3 shrink-0 text-muted-foreground"
                aria-label="Recurring"
              />
            )}
            {expense.autoGenerated && (
              <Badge variant="outline" className="shrink-0 px-1.5 py-0 text-[10px]">
                auto
              </Badge>
            )}
          </div>
          {meta.length > 0 && (
            <p className="truncate text-xs text-muted-foreground">
              {meta.join(" · ")}
            </p>
          )}
        </div>
      </div>
      <div className="flex shrink-0 items-center gap-3">
        <span className="hidden text-xs text-muted-foreground sm:inline">
          {formatDate(expense.date)}
        </span>
        <span className="tabular-nums font-medium">
          {formatMoney(expense.amountPaisa)}
        </span>
        <div className="flex opacity-0 transition-opacity focus-within:opacity-100 group-hover:opacity-100">
          <button
            onClick={() => onEdit(expense)}
            aria-label="Edit expense"
            className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
          >
            <Pencil className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={handleDelete}
            aria-label="Delete expense"
            className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-destructive"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
    </div>
  );
}
