"use client";

import * as React from "react";
import { Pencil, Trash2, Repeat, Check, X } from "lucide-react";
import { toast } from "sonner";
import { cn, formatDate } from "@/lib/utils";
import { formatMoney } from "@/lib/money";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useBudgetStore } from "../store";
import { CategoryPicker } from "./category-picker";
import { PAYMENT_METHODS } from "../constants";

export function ExpenseRow({ expense, category, categories }) {
  const updateExpense = useBudgetStore((s) => s.updateExpense);
  const deleteExpense = useBudgetStore((s) => s.deleteExpense);
  const undoDeleteExpense = useBudgetStore((s) => s.undoDeleteExpense);
  const [editing, setEditing] = React.useState(false);
  const [draft, setDraft] = React.useState(null);

  function startEdit() {
    setDraft({
      amount: (expense.amountPaisa / 100).toString(),
      categoryId: expense.categoryId,
      note: expense.note || "",
      paymentMethod: expense.paymentMethod,
      date: expense.date,
    });
    setEditing(true);
  }

  async function saveEdit() {
    try {
      await updateExpense(expense._id, draft);
      setEditing(false);
    } catch (err) {
      toast.error(err.message || "Could not save changes.");
    }
  }

  async function handleDelete() {
    try {
      const removed = await deleteExpense(expense._id);
      toast("Expense deleted.", {
        action: {
          label: "Undo",
          onClick: () => undoDeleteExpense(removed),
        },
      });
    } catch {
      toast.error("Could not delete expense.");
    }
  }

  if (editing) {
    return (
      <div className="space-y-2 rounded-lg border bg-accent/30 p-3">
        <div className="flex flex-wrap items-center gap-2">
          <Input
            type="number"
            step="0.01"
            value={draft.amount}
            onChange={(e) => setDraft((d) => ({ ...d, amount: e.target.value }))}
            className="h-8 w-28"
          />
          <Input
            type="date"
            value={draft.date}
            onChange={(e) => setDraft((d) => ({ ...d, date: e.target.value }))}
            className="h-8 w-40"
          />
          <Select
            className="h-8 w-40"
            value={draft.paymentMethod}
            onChange={(e) => setDraft((d) => ({ ...d, paymentMethod: e.target.value }))}
          >
            {PAYMENT_METHODS.map((p) => (
              <option key={p.id} value={p.id}>
                {p.label}
              </option>
            ))}
          </Select>
        </div>
        <CategoryPicker
          categories={categories}
          value={draft.categoryId}
          onChange={(categoryId) => setDraft((d) => ({ ...d, categoryId }))}
        />
        <Input
          placeholder="Note"
          value={draft.note}
          onChange={(e) => setDraft((d) => ({ ...d, note: e.target.value }))}
          className="h-8"
        />
        <div className="flex justify-end gap-1.5">
          <button
            onClick={() => setEditing(false)}
            className="flex items-center gap-1 rounded-md px-2 py-1 text-xs text-muted-foreground hover:bg-accent"
          >
            <X className="h-3.5 w-3.5" />
            Cancel
          </button>
          <button
            onClick={saveEdit}
            className="flex items-center gap-1 rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground hover:bg-primary/90"
          >
            <Check className="h-3.5 w-3.5" />
            Save
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="group flex items-center justify-between gap-3 rounded-lg px-2 py-2.5 text-sm hover:bg-accent/50">
      <div className="flex min-w-0 items-center gap-3">
        <span
          className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-base"
          style={{ background: `${category?.color || "#64748b"}22` }}
          aria-hidden="true"
        >
          {category?.icon || "🏷️"}
        </span>
        <div className="min-w-0">
          <div className="flex items-center gap-1.5">
            <span className="truncate font-medium">
              {category?.name || "Uncategorized"}
            </span>
            {expense.isRecurring && (
              <Repeat className="h-3 w-3 shrink-0 text-muted-foreground" aria-label="Recurring" />
            )}
            {expense.autoGenerated && (
              <Badge variant="outline" className="shrink-0 px-1.5 py-0 text-[10px]">
                auto
              </Badge>
            )}
          </div>
          {expense.note && (
            <p className="truncate text-xs text-muted-foreground">{expense.note}</p>
          )}
        </div>
      </div>
      <div className="flex shrink-0 items-center gap-3">
        <span className="hidden text-xs text-muted-foreground sm:inline">
          {formatDate(expense.date)}
        </span>
        <span className="tabular-nums font-medium">{formatMoney(expense.amountPaisa)}</span>
        <div className="flex opacity-0 transition-opacity group-hover:opacity-100">
          <button
            onClick={startEdit}
            aria-label="Edit expense"
            className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
          >
            <Pencil className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={handleDelete}
            aria-label="Delete expense"
            className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-destructive"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
    </div>
  );
}
