import mongoose from "mongoose";

const RecurrenceSchema = new mongoose.Schema(
  {
    frequency: {
      type: String,
      enum: ["weekly", "monthly", "yearly"],
      required: true,
    },
    dayOfMonth: Number, // 1-31, for monthly
    weekday: Number, // 0 (Sun) - 6 (Sat), for weekly
    nextRunDate: String, // 'YYYY-MM-DD' local date — when the cron should next generate an entry
  },
  { _id: false }
);

const ExpenseSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    amountPaisa: { type: Number, required: true }, // integer, smallest unit — never a float
    currency: { type: String, default: "NPR" },
    categoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
      index: true,
    },
    date: { type: String, required: true }, // 'YYYY-MM-DD' — local calendar date, never UTC-shifted
    note: { type: String, trim: true },
    paymentMethod: {
      type: String,
      enum: ["cash", "card", "bank_transfer", "wallet", "other"],
      default: "cash",
    },
    tags: [String],
    isRecurring: { type: Boolean, default: false },
    recurrence: RecurrenceSchema,
    autoGenerated: { type: Boolean, default: false },
    // The recurring template this entry was generated from, if any.
    sourceRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Expense",
      default: null,
    },
    // Soft-delete powers the undo toast instead of a confirm dialog.
    deletedAt: { type: Date, default: null },
    /**
     * How the entry was captured: typed, spoken, or imported from a bank
     * statement (`import:<bank>`). Absent on older documents, read as manual.
     */
    source: { type: String, trim: true, maxlength: 40 },
    /**
     * Statement-import dedupe key (date + amount + direction + normalised
     * description + occurrence). Only imported rows carry one.
     */
    fingerprint: { type: String },
  },
  { timestamps: true }
);

// Every real query is {userId, deletedAt: null, date: range} — the two
// separate {userId,date} and {userId,deletedAt} indexes each covered only
// half of it, so Mongo filtered the rest in memory. Order matters:
// equality fields (userId, deletedAt) precede the range field (date).
ExpenseSchema.index({ userId: 1, deletedAt: 1, date: -1 });
ExpenseSchema.index({ userId: 1, deletedAt: 1, categoryId: 1, date: -1 });
// Sorting the list by amount within a filtered window.
ExpenseSchema.index({ userId: 1, deletedAt: 1, amountPaisa: -1 });
// Re-importing a statement looks these up in bulk. Partial, so the manual
// entries (the vast majority) cost nothing in the index.
ExpenseSchema.index(
  { userId: 1, fingerprint: 1 },
  { partialFilterExpression: { fingerprint: { $type: "string" } } }
);

export default mongoose.models.Expense ||
  mongoose.model("Expense", ExpenseSchema);
