import mongoose from "mongoose";

const RecurrenceSchema = new mongoose.Schema(
  {
    frequency: {
      type: String,
      enum: ["weekly", "monthly", "yearly"],
      required: true,
    },
    dayOfMonth: Number, // 1-31, for monthly
    weekday: Number, // 0 (Sun) - 6 (Sat), for weekly
    nextRunDate: String, // 'YYYY-MM-DD' local date — when the cron should next generate an entry
  },
  { _id: false }
);

const ExpenseSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    amountPaisa: { type: Number, required: true }, // integer, smallest unit — never a float
    currency: { type: String, default: "NPR" },
    categoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Category",
      required: true,
      index: true,
    },
    date: { type: String, required: true }, // 'YYYY-MM-DD' — local calendar date, never UTC-shifted
    note: { type: String, trim: true },
    paymentMethod: {
      type: String,
      enum: ["cash", "card", "bank_transfer", "wallet", "other"],
      default: "cash",
    },
    tags: [String],
    isRecurring: { type: Boolean, default: false },
    recurrence: RecurrenceSchema,
    autoGenerated: { type: Boolean, default: false },
    // The recurring template this entry was generated from, if any.
    sourceRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Expense",
      default: null,
    },
    // Soft-delete powers the undo toast instead of a confirm dialog.
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

ExpenseSchema.index({ userId: 1, date: 1 });
ExpenseSchema.index({ userId: 1, categoryId: 1, date: 1 });
ExpenseSchema.index({ userId: 1, deletedAt: 1 });

export default mongoose.models.Expense ||
  mongoose.model("Expense", ExpenseSchema);
